// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWB78r9s9dE2835uT7X0pxTykTp4bVtWI',
    appId: '1:920337396573:web:66f9c70338ba6851ec6eb4',
    messagingSenderId: '920337396573',
    projectId: 'fruit-hub-195d3',
    authDomain: 'fruit-hub-195d3.firebaseapp.com',
    storageBucket: 'fruit-hub-195d3.firebasestorage.app',
    measurementId: 'G-0T71S2W01L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMOIKBhXD6Z79LXzeoF2osHHhcBAjJF2k',
    appId: '1:920337396573:android:e5a7cf8aa12f2af7ec6eb4',
    messagingSenderId: '920337396573',
    projectId: 'fruit-hub-195d3',
    storageBucket: 'fruit-hub-195d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2PU09GByzhidn0gvOlldvK4Yj4NFzTCE',
    appId: '1:920337396573:ios:4240fe7bb56f1443ec6eb4',
    messagingSenderId: '920337396573',
    projectId: 'fruit-hub-195d3',
    storageBucket: 'fruit-hub-195d3.firebasestorage.app',
    androidClientId: '920337396573-jdh9sb4ivca4aeh4n51pimgkkp3oee9p.apps.googleusercontent.com',
    iosClientId: '920337396573-fg1iuoogcj8hjpgncdi2qeag3hkhh09f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWB78r9s9dE2835uT7X0pxTykTp4bVtWI',
    appId: '1:920337396573:web:3c9dbe62acb18749ec6eb4',
    messagingSenderId: '920337396573',
    projectId: 'fruit-hub-195d3',
    authDomain: 'fruit-hub-195d3.firebaseapp.com',
    storageBucket: 'fruit-hub-195d3.firebasestorage.app',
    measurementId: 'G-J1DEXSFLVR',
  );
}
